spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: rkdgus3835

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace